### ISSUE TITLE
4. 실천 Todo

### ISSUE THREAD

**Issue by jung0115** [womentech-hackathon/Womentech_AOS#9]
- [x] 제목
- [x] 이용방법 버튼
- [ ] 주차
  - [x] 주차 이동 버튼
  - [x] 주차별 날짜 리스트
  - [x] 날짜별 완료 유무 표시
  - [x] 오늘의 날짜 표시
  - [x] 날짜별 실천사항 조회 api 연동
  - [ ] 실천사항 완료 api 연동
- [ ] 실천 사항
  - [x] RecyclerView
  - [x] 체크
  - [ ] 완료 팝업
  - [x] 실천 사항 모두 보기
  - [ ] 수정, 종료 BottomSheet
- [ ] 실천 사항 추가
  - [x] Recyclerview
  - [x] 추가 버튼
  - [ ] 생성 api 연동
- [x] 실천 사항 확인
  - [x] 실천 중
  - [x] 실천 종료
